# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=7.3.2
maven_group=com.tangykiwi.kiwiclient
archives_base_name=kiwiclient

# Dependencies
fabric_api_version=0.154.2+26.2

# Sodium (https://github.com/CaffeineMC/sodium-fabric)
sodium_version=mc26.2-0.9.1-fabric