# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=8.3.4
maven_group=com.tangykiwi.kiwiclient
archives_base_name=kiwiclient

# Dependencies
fabric_api_version=0.161.0+26.3

# Sodium (https://github.com/CaffeineMC/sodium-fabric)
sodium_version=mc26.3-0.9.2-fabric