# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=6.1.4
maven_group=com.tangykiwi.kiwiclient
archives_base_name=kiwiclient

# Dependencies
fabric_api_version=0.148.0+26.1.2

# Sodium (https://github.com/CaffeineMC/sodium-fabric)
sodium_version=mc26.1.2-0.8.11-fabric